Blog app - integration specs for views
VuDej/Blog pull request #12
Opened 2022-05-10 16:46 UTC by VuDej

Hi,
- fixed errors in spec/module test adding counters coulms to default: 0, and ading localhost 3000 in devise test.rb file
- created file login_spec.rb and test for page
- created file user_index_spec.rb and test for user/index page
- created file user_show_spec.rb and test for user/show page
- created file post_index_spec.rb and test for post/index page
- created file post_show_spec.rb and test for post/show page
Tests take all integrations on page. Used capybara for testing, and login user.
If  logged-in user can see all interactions in given page, test wrote and passed.

2022-05-10 18:46 UTC, mmsesay requested changes
Hi @VuDej, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._

You can also consider:
-[ ] Drafting a brief description of your project in the readme.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-10 18:46 UTC, mmsesay commented on spec/integration/user_index_spec.rb
> +  end
- [ ] You did well writing these tests. However, I guess you forgot to write tests for the following bullet points under the User index page:

* I can see the profile picture for each user.
* I can see the number of posts each user has written.
* When I click on a user, I am redirected to that user's show page.

2022-05-10 18:46 UTC, mmsesay commented on spec/integration/user_show_spec.rb
> +end
- [ ] It will be nice to write the following tests are required for this project specifically for this User show page:

* Tests that assert you can see the user's profile picture
* Tests that assert you can see the user's first 3 posts.
* Tests that redirect to the post's show page when you click on a user's post.
* Tests that redirect to the user's post's index page when you click on a **see all posts**.

2022-05-10 18:46 UTC, mmsesay commented on spec/integration/post_index_spec.rb
> +end
- [ ] Please also try adding a test for the following bullet points:

* Tests that asserts you can see the user's profile picture.
* Tests that redirects to the post's show page when you click on a post.

2022-05-10 18:46 UTC, mmsesay commented on spec/integration/post_show_spec.rb
> +end
- [ ] Please add the following tests also:

* Tests that asserts you can see the username of each commentor.
* Tests that asserts you can see the comment each commentor left.

2022-05-10 21:39 UTC, medaminedev66 requested changes
Hi @VuDej 😃,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- The integration tests run successfully.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-10 21:39 UTC, medaminedev66 commented on spec/integration/user_show_spec.rb
> +  end
- [ ] Following the project requirements, and as requested by the previous reviewer, you should also add tests that redirect to the post's show page when you click on a user's post.

2022-05-11 05:08 UTC, Meltrust approved these changes
Hi @VuDej,


## Wow, you did it 🎉
![image](https://user-images.githubusercontent.com/57421823/167773178-d966774d-663b-441e-a8b3-3f07d3886659.png)

![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the test requested by the previous reviewer,  💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-11 05:13 UTC, merged